name: Portfolio
description: "My own Portfolio"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  animate_gradient: ^0.0.3
  simple_gradient_text: ^1.3.0
  font_awesome_flutter: ^10.7.0
  animated_text_kit: ^4.2.2
  rive: ^0.13.9
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_floating_bottom_bar: ^1.2.0
  flutter_custom_carousel: ^0.1.0+1
  infinite_carousel: ^1.1.1
  url_launcher: ^6.1.10
  hovering: ^1.0.4
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  google_sign_in: ^6.2.1
  flutter_login_facebook: ^2.0.1
  awesome_snackbar_content: ^0.1.3
  cloud_firestore: ^5.0.2
  sidebarx: ^0.17.1
  flutter_staggered_grid_view: ^0.7.0
  video_player: ^2.4.0
  visibility_detector: ^0.3.3
  flashy_tab_bar2: ^0.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/icons/
    - assets/images/logo/
    - assets/images/certifications/
    - assets/images/skills/
    - assets/images/menu/
    - assets/rive/
    - assets/projects/


  fonts:
     - family: Poppinns
       fonts:
         - asset: assets/fonts/Poppins-BlackItalic.ttf
         - asset: assets/fonts/Poppins-BoldItalic.ttf
         - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
         - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
         - asset: assets/fonts/Poppins-Italic.ttf
         - asset: assets/fonts/Poppins-LightItalic.ttf
         - asset: assets/fonts/Poppins-MediumItalic.ttf
         - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
         - asset: assets/fonts/Poppins-ThinItalic.ttf
           style: italic
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Bold.ttf
         - asset: assets/fonts/Poppins-Black.ttf
         - asset: assets/fonts/Poppins-Black.ttf
         - asset: assets/fonts/Poppins-Bold.ttf
         - asset: assets/fonts/Poppins-ExtraBold.ttf
         - asset: assets/fonts/Poppins-ExtraLight.ttf
         - asset: assets/fonts/Poppins-Light.ttf
         - asset: assets/fonts/Poppins-Medium.ttf
         - asset: assets/fonts/Poppins-SemiBold.ttf
         - asset: assets/fonts/Poppins-Thin.ttf
           weight: 700